- name: Ansible
  gather_facts: false
  hosts: all
  tasks:
    - name: "Create ansible user"
      user:
        name: ansible
        shell: /bin/bash
        append: yes
    - name: "Set authorized key taken from file"
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', 'ansible_id_rsa.pub') }}"
    - name: "Install sudo"
      script: scripts/install.sh
    - name: Add user to sudoers file
      lineinfile:
        path: /etc/sudoers
        regexp: '^ansible'
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
