---
  - name: Initialize the Cluster
    shell: kubeadm init
      #    args:
      #chdir: $HOME
      #creates: cluster_initialized.txt
  
  - name: Configure kubectl
    file:
      path: $HOME/.kube
      state: directory
      mode: 0755

  - name: Prepare configuration for kubectl
    copy:
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      remote_src: yes
      owner: root
  
  - name: Enable kubectl autocompletion
    shell: kubectl completion bash | tee /etc/bash_completion.d/kubectl > /dev/null

  - name: Install Pod network
    shell: kubectl apply -f "https://docs.projectcalico.org/manifests/calico.yaml "

  - name: Get the token for joining the worker nodes
    shell: kubeadm token create  --print-join-command
    register: kubernetes_join_command

  - name: Print information about kubernetes token
    ansible.builtin.debug:
      msg: "{{ kubernetes_join_command.stdout }}"

  - name: Copy join command to local file
    local_action: copy content="{{ kubernetes_join_command.stdout }}" dest="/tmp/kubernetes_join_command" mode=0777	
...
